project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!materials/workshop/"

website:
  title: "Introduzione all'analisi di RNASeq"
  twitter-card:
    card-style: summary_large_image
    description: "Corso Revelo - Analisi di dati di trascrittomica con R"
  page-footer:
    left: "This page was built with ❤️, [R](https://cran.r-project.org) and [Quarto](https://quarto.org/) by Marco Chiapello."
  navbar:
    background: "#447099"
    logo: "materials/images/revelo.png"
    left:
      - text: Slides
        menu: 
          - href: materials/M1_intro.qmd
            text: "Modulo I: Introduzione al corso"
          - href: materials/02-Day02.qmd
            text: "Secondo giorno"
    right: 
      - text: "Revelo DataLabs"
        href: https://revelodatalabs.com
      - icon: github
        href: https://github.com/mchiapello/202304_REVELO_Torvergata
  sidebar: 
    style: docked
    contents: 
      - section: "Corso"
        contents: 
          - href: materials/01-Day01_RiepilogoR.qmd
            text: "Riepilogo R"
          - href: materials/01-Day01.qmd
            text: "Primo giorno"
          - href: materials/02-Day02.qmd
            text: "Secondo giorno"
      - section: "Materiale aggiuntivo"
        contents: 
          - href: materials/test-layout.qmd
            text: "Letture"
          - href: materials/02-Day02.qmd
            text: "Risorse esterne"      

format:
  html:
    theme: 
      - litera
      - style.css
    toc: true